development:
  adapter: postgresql
  encoding: utf8
  database: raffler_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: utf8
  database: raffler_test
  pool: 5
  username: 
  password:
